name: Pella Full Auto

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4

      - name: 🟢 Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install
        run: |
          npm install
          npx playwright install --with-deps

      - name: 🚀 Run
        run: node pella-auto.js
        env:
          ACCOUNT_JSON: ${{ secrets.ACCOUNT_JSON }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
